"""yt-dlp powered TikTok download backend.

Provides async wrappers around yt-dlp for downloading TikTok videos.
Used as a fallback when the native API is blocked by TikTok's WAF.

The cookie is read from ``parameter.cookie_dict_tiktok`` and converted
to a Netscape cookie file for yt-dlp consumption.
"""
from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, List, Optional

if TYPE_CHECKING:
    from src.config import Parameter
    from src.record import BaseLogger, LoggerManager

__all__ = ["YtDlpTikTok"]

# Prefer the Python 3.12 that has yt-dlp installed
_PYTHON_312 = r"C:\Users\LUKE\AppData\Local\Programs\Python\Python312\python.exe"


def _get_python() -> str:
    """Return the Python executable that has yt-dlp installed."""
    if os.path.isfile(_PYTHON_312):
        return _PYTHON_312
    return sys.executable


def _cookie_dict_to_netscape(cookie_dict: dict, filepath: str) -> str:
    """Write cookies from parameter.cookie_dict_tiktok to Netscape format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by DouK-Downloader yt-dlp bridge",
        "",
    ]
    for name, value in cookie_dict.items():
        domain = ".tiktok.com"
        flag = "TRUE"
        path = "/"
        secure = "TRUE"
        expires = "1806170703"  # ~2027
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    Path(filepath).write_text("\n".join(lines), encoding="utf-8")
    return filepath


class YtDlpTikTok:
    """Download TikTok videos via yt-dlp subprocess."""

    def __init__(
        self,
        parameter: "Parameter",
        logger: "BaseLogger | LoggerManager",
    ):
        self.parameter = parameter
        self.logger = logger
        self.root = parameter.root or Path(".")
        self._python = _get_python()

    def _make_cookie_file(self) -> Optional[str]:
        """Create a temp Netscape cookie file from parameter cookies."""
        cookie_dict = self.parameter.cookie_dict_tiktok
        if not cookie_dict:
            self.logger.warning("No TikTok cookies available for yt-dlp")
            return None
        tmp = tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".txt",
            prefix="ytdlp_cookies_",
            delete=False,
            encoding="utf-8",
        )
        tmp.close()
        _cookie_dict_to_netscape(cookie_dict, tmp.name)
        return tmp.name

    async def download_urls(self, urls: List[str]) -> List[str]:
        """Download one or more TikTok URLs.

        Returns list of successfully downloaded file paths.
        """
        if not urls:
            return []

        cookie_file = self._make_cookie_file()
        downloaded = []

        try:
            for url in urls:
                result = await self._download_single(url, cookie_file)
                if result:
                    downloaded.append(result)
        finally:
            if cookie_file:
                try:
                    os.unlink(cookie_file)
                except OSError:
                    pass

        return downloaded

    async def _download_single(
        self, url: str, cookie_file: Optional[str]
    ) -> Optional[str]:
        """Download a single URL via yt-dlp. Returns the output file path."""
        output_dir = Path(self.root)
        output_dir.mkdir(parents=True, exist_ok=True)

        output_template = str(
            output_dir / "%(uploader)s_%(id)s_%(title).80s.%(ext)s"
        )

        cmd = [
            self._python,
            "-m",
            "yt_dlp",
            "--no-check-certificates",
            "--no-warnings",
            "--newline",
            "--print-to-file",
            "after_move:filepath",
            str(output_dir / "_ytdlp_last_path.txt"),
            "-o",
            output_template,
        ]

        if cookie_file:
            cmd.extend(["--cookies", cookie_file])

        cmd.append(url)

        self.logger.info(f"yt-dlp: downloading {url}")

        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(output_dir),
            )

            stdout, stderr = await asyncio.wait_for(
                proc.communicate(), timeout=300
            )

            stdout_text = stdout.decode("utf-8", errors="replace")
            stderr_text = stderr.decode("utf-8", errors="replace")

            if proc.returncode == 0:
                # Try to read the output filepath
                last_path_file = output_dir / "_ytdlp_last_path.txt"
                if last_path_file.exists():
                    filepath = last_path_file.read_text(
                        encoding="utf-8"
                    ).strip()
                    last_path_file.unlink(missing_ok=True)
                    if filepath and Path(filepath).exists():
                        size_mb = Path(filepath).stat().st_size / (1024 * 1024)
                        self.logger.info(
                            f"yt-dlp: ✅ Downloaded {Path(filepath).name} "
                            f"({size_mb:.1f} MB)"
                        )
                        self.logger.info(f"yt-dlp: path = {filepath}")
                        return filepath

                # Fallback: parse stdout for filename
                for line in stdout_text.splitlines():
                    if "[download]" in line and "has already been downloaded" in line:
                        self.logger.info(f"yt-dlp: file already exists")
                        return None
                    if "Destination:" in line:
                        dest = line.split("Destination:", 1)[1].strip()
                        if Path(dest).exists():
                            self.logger.info(
                                f"yt-dlp: ✅ Downloaded {Path(dest).name}"
                            )
                            return dest

                self.logger.info("yt-dlp: completed (output path unknown)")
                return None
            else:
                # Log only the last few lines of stderr
                err_lines = stderr_text.strip().splitlines()
                for line in err_lines[-5:]:
                    self.logger.error(f"yt-dlp: {line}")
                return None

        except asyncio.TimeoutError:
            self.logger.error(f"yt-dlp: download timed out (300s) for {url}")
            return None
        except FileNotFoundError:
            self.logger.error(
                f"yt-dlp: Python not found at {self._python}. "
                f"Install yt-dlp: pip install yt-dlp"
            )
            return None
        except Exception as e:
            self.logger.error(f"yt-dlp: unexpected error: {e}")
            return None
